#!/bin/bash

decktape --size 1600x900 automatic intro.html intro.pdf
decktape --size 1600x900 automatic odes.html odes.pdf
decktape --size 1600x900 automatic linear-systems.html linear-systems.pdf
decktape --size 1600x900 automatic controllability.html controllability.pdf
decktape --size 1600x900 automatic asymptotic-stabilization.html asymptotic-stabilization.pdf
decktape --size 1600x900 automatic optimal-control.html optimal-control.pdf
