#!/usr/bin/env python

"""
Parallel build of the HTML slide decks and Jupyter notebooks (and optionally PDF slide decks)
"""

# Python Standard Library
import shlex
import subprocess
import sys

def sh(cmd):
    return subprocess.Popen(shlex.split(cmd)) 

targets = [
    "intro",
    "models",
    "simulation",
    "well-posedness",
    "asymptotic",
    "LTI-models",
    "internal-dynamics",
    "IO-dynamics",
    "controllability",
    "asymptotic-stabilization",
    "optimal-control",
    "observers",
]

processes = []

for target in targets:
    cmd = ["./build.py"]
    if "--fast" in sys.argv[1:]:
        cmd.append("--fast")
    cmd.append(f"{target}.md")
    processes.append(subprocess.Popen(cmd)) # start in the background

status = (0 if all(p.wait() == 0 for p in processes) else 1)
if status != 0:
    sys.exit(status)

if "--pdf" in sys.argv[1:]:
    print("Building PDF slide decks")
    processes = []

    for target in targets:
        cmd = f"decktape --chrome-arg=--no-sandbox --size 1600x900 automatic {target}.html {target}.pdf"
        process = sh(cmd)
        processes.append(process)

    sys.exit(0 if all(p.wait() == 0 for p in processes) else 1)