#!/usr/bin/env python

"""
Parallel build of the HTML slide decks and Jupyter notebooks
"""

# Standard Python Library
import subprocess
import sys

targets = [
    "intro",
    "models",
    "simulation",
    "well-posedness",
    "asymptotic",
    "LTI-models",
    "internal-dynamics",
    "IO-dynamics",
    "controllability",
    "asymptotic-stabilization",
    "optimal-control",
    "observers",
]

processes = [subprocess.Popen(["./build.py", f"{target}.md"]) for target in targets]

sys.exit(0 if all(p.wait() == 0 for p in processes) else 1)
