#!/bin/bash

rm -f *.html *.ipynb images/*.svg # generated, untracked files in master
git checkout gh-pages
git merge master -s recursive -Xtheirs
./build
git *.html add *.ipynb images/*.svg
git commit -am "new build"
git push
git checkout master
